---
# Package repository to use
openio_sds_release: "18.10"

# Namespace
namespace: OPENIO
namespace_meta1_digits: "2"
namespace_storage_policy: THREECOPIES
namespace_chunk_size_megabytes: 100
openio_replicas: 3
# Service locations (must be ended by a dot)
#openio_location_room:
#openio_location_rack:
openio_location_server: "{{ ansible_hostname }}."

openio_s3_region: "us-east-1"

# Network
openio_bind_interface: "{{ ansible_default_ipv4.alias }}"
openio_bind_address: "{{ ansible_default_ipv4.address }}"

# S3 users (tempauth)
openio_oioswift_users:
  - name: "demo:demo"
    password: "DEMO_PASS"
    roles:
      - admin

# sysctl
openio_manage_sysctl: true

# Account
default_account: openio

# Maintenance Mode:
openio_maintenance_mode: false

# Sysctl
openio_sysctl_managed: true
openio_sysctl_entries:
  net.ipv4.ip_local_port_range: 8192 65535
  net.ipv4.tcp_fastopen: 1
  net.ipv4.tcp_mtu_probing: 1
  net.ipv4.tcp_rfc1337: 1
  net.ipv4.tcp_sack: 1
  net.ipv4.tcp_syncookies: 0
  net.ipv4.tcp_timestamps: 1
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_window_scaling: 1
  kernel.pid_max: 196608


########
# Special needs
# ---- Low memory nodes (ARM, docker, ...)
#openio_account_workers: 1
#openio_oioswift_workers: 1
#namespace_meta1_digits: "1"
#openio_event_agent_workers: 1
#openio_zookeeper_parallel_gc_threads: 1
#openio_zookeeper_memory: "256M"
#openio_minimal_score_for_volume_admin_bootstrap: 5
#openio_minimal_score_for_directory_bootstrap: 5
# ---- End Low memory nodes
...
