---
# Set to true to allow pre-checks to fail and continue deployment
openio_ignore_assert_errors: false

# Set of linux distribution supported
openio_distribution_supported:
  - RedHat
  - CentOS
  - Fedora
  - Ubuntu

openio_release_supported:
  - "18.04"
  - "18.10"

# openio's GID
openio_group_openio_gid: 220
# openio's UID
openio_user_openio_uid: 120

# NTP
ntp_enabled: true
ntp_manage_config: true
ntp_timezone: "Europe/Paris"
ntp_area: ".fr"
ntp_servers:
  - "0{{ ntp_area }}.pool.ntp.org iburst"
  - "1{{ ntp_area }}.pool.ntp.org iburst"
  - "2{{ ntp_area }}.pool.ntp.org iburst"
  - "3{{ ntp_area }}.pool.ntp.org iburst"
ntp_restrict:
  - "127.0.0.1"
  - "::1"

# for proxies by example
openio_environment: {}

# Install require on targets
openio_manage_os_requirement: true

# mirror
openio_mirror: "mirror.openio.io"
...
